name: chip_dropdown
description: A new Flutter package project.
version: 2.5.0
homepage: https://github.com/jithutechfriar/chip_dropdown_flutter_package.git

environment:
  sdk: ">=2.19.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

# use this path for local access to this package
#   chip_dropdown:
#     path: ../packages/chip_dropdown

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

